name: Test Deployment

on:
  release:
    types: [prereleased]

jobs:
  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-latest
    steps:
      - name: Declare commit hash variable
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          data: "{ 'environment': 'test', 'version': 'sha-${{ steps.vars.outputs.sha_short }}', 'port': '2'}"
