# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ xxxx ]

jobs:
  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js 14
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: 14
  #   - name: Branch name as environment Variable
  #     run: echo "BRANCH=${GITHUB_REF##*/}"  >> $GITHUB_ENV
  #   - run: npm ci
  #   - run: npm test
  # deployment:
  #   runs-on: ubuntu-latest

  #   environment:
  #     name: production
  #     url: https://github.com
